# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Application-Plugin-Output-XSV
version:      0.9
version_from: XSV.pm
installdirs:  site
requires:
    CGI::Application:              0
    Test::More:                    0
    Text::CSV_XS:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
